### PR TITLE
Add blog post about the RIKEN HPC Summer School

### PR DESCRIPTION
**Pull request by keichi**
@boom10899 @Kundjanasith Do you have a photo you can add to the post?

### CODE REVIEW

**Comment by boom10899** [comment]
We have a group photos that took in Zoom meeting. I'll sent you via Slack. We'll also receive a certificate of attendance, but I don't know when we will receive it.

**Comment by keichi** [comment]
I think we shouldn't post other people's photos without permission. Let's add your certificate once you receive it.

**Comment by boom10899** [comment]
Thank you very much.

**Review by boom10899 — APPROVED** [review]

**Review by Kundjanasith — APPROVED** [review]
Thank you very much, I still waiting for the certificate from RIKEN.

**Review by boom10899 — APPROVED** [review]

**Comment by boom10899** [comment]
@keichi @Kundjanasith Please review the figure. If you have any comment, please let me know. I'll modify it before merge into master.

**Review by Kundjanasith — APPROVED** [review]
Thank you very much, It looks good for me.

**Comment by keichi** [comment]
@boom10899 Can you remove `content/en/post/boom-tem-riken-hpc-summer-school/featured.jpg`? The picture from the Japanese version will be used by default. Otherwise it looks good.

**Comment by keichi** [comment]
Thanks, please merge

**Comment by boom10899** [comment]
I already merged. Thank you very much.

**Pull request merged**
